### ISSUE TITLE
Ties

### ISSUE THREAD

**Issue by thedpws** [thedpws/pitcher#16]
Ties are necessary to extend note durations across multiple measures. 
1. Represent this in our data structure, probably as a list of neighbors within the note class.

2. Another solution is to introduce a `Note`-level class (alongside `Note` and `Chord`) called `Tie` which takes multiple `Note` objs as parameters.
Example: `Measure([ Note('A', 1), Tie( Note('A#', 2.0), Note('A#', 0.5) ) ])`

3. OR you can have a method on `Note` called `tie(duration: float) -> Tie`.
In usage, it would look like `Measure([ Note('A', 1), Note('A#', 2.0).tie(0.5) ])` 

If we do a `Tie` class, it should inherit from `Note` and have an overriden `__iter__` function that iterates over its inner notes.

Related #15

**Comment by BrianMcDowell** [comment]
Current "playing" behavior already simulates this effect, so the easiest solution for playing is to set a boolean "tie" attribute within the note class. If tie is on then keep beat_keyoff at current programming (line 80 of playing.py) but if flag is off subtract an appropriate interval from beat_keyoff to create distinction between notes. I would expect an appropriate interval to be 1/64 or 1/128 of a beat, but this could be adjustable based on the music. Factors in the interval could be whether the piece is staccato or legato.

**Comment by thedpws** [comment]
Closed by #75
