### ISSUE TITLE
Export score to PDF

### ISSUE THREAD

**Issue by thedpws** [thedpws/pitcher#20]
`show_score` currently uses *mingus* as an interface to lilypond to save the sheet music as a temporary PNG for brief showing.

*mingus* has similar functions for exporting lilypond to PDF's. Allow users to `.save` any piece of our data structure. Allow passing in parameters such as filename and maybe optionally filetype ('pdf', 'png').

**Comment by MenkeTechnologies** [comment]
im almost done

**Comment by thedpws** [comment]
Closed by PR #31
