### ISSUE TITLE
Documentation Should Read Opposite Direction

### ISSUE THREAD

**Issue by BrianMcDowell** [thedpws/pitcher#48]
I think the documentation flow makes more sense working from the top of the hierarchy down (Score -> Note) instead of from the bottom up. When using pitchr you would first create a Score then fill it with a Part, then add a Clef to the Part, then a Measure to the Clef, etc. Learning about a note first doesn't make sense because you don't have a container to put it in.

**Comment by thedpws** [comment]
I think it's better to think of the most elementary things like Notes and Measures first, and those are still things the user can play with, even without wrapping it in their containers. We don't expect everyone to be interested in making Scores, but we can definitely expect them to be making Notes
